### PR TITLE
Swift 3.0 Compatibility

### PR DESCRIPTION
**Pull request by jedmund**
This branch is intended to add Swift 3.0 compatibility. For the most part it's done—this compiles—but there's a runtime error I'm hoping to get some hope with.

Currently, `ValidatableInterfaceElement` uses Objective-C associated objects to store the `ValidatableRuleSet` and `ValidationHandler` on UIKit elements to refer to later. In order to do this in Swift, we're using an `NSObject` wrapper class.

The wrapper class was initially causing some compilation issues with `ValidationRuleSet`, so I removed the `Box` calls from that property and everything seems to be okay.

```swift
public var validationRules: ValidationRuleSet<InputType>? {
    get {
        let rules = objc_getAssociatedObject(self, &ValidatableInterfaceElementRulesKey) as? ValidationRuleSet<InputType>
        return rules
    }
    set(newValue) {
        if let n = newValue {
            objc_setAssociatedObject(self, &ValidatableInterfaceElementRulesKey, n, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
}
```
> This is where the `Box` was removed.

The problem comes with `ValidationHandler`. This does still need the `Box` class because closures are not Objective-C objects and cannot be stored as such. Setting and getting the associated object (containing the closure) seems to work fine, but calling the closure causes a runtime error on validation. This is where I'm stuck. I'm not sure what the issue is here, or why it broke in Swift 3.0, but I think it might have to do with types?

```swift
public func validate(rules rs: ValidationRuleSet<InputType>) -> ValidationResult {
    let result = Validator.validate(input: inputValue, rules: rs)
    if let h = validationHandler {
        // This is the method that is causing a crash.
        // We've received the handler closure as an associated object,
        // but calling it causes exc_bad_access.
        h(result, self)
    }
    return result
}
```
> This is where the runtime crash occurs.

Anyway, any help is greatly appreciated! Really looking forward to having Swift 3.0 support for this great library.

### CODE REVIEW

**Comment by jedmund** [comment]
I managed to fix the crash with 1cd456c. The commit message there is copied here for convenience, as it describes what the problem was:

>Turns out, the Box subclass was not needed anymore either as Swift 3
allows you to cast anything into AnyObject. This removes our need to
convert the validationHandler closure into an object to store with
Objective-C.

>However, the initial crash was caused by what seems to be a bug in how
NSObject handles Generics, although I don’t know the exact nature of
it. By removing the NSObject subclass from Box<T>, we no longer crashed
on validation.

>Big thanks to mikeash on #swift-lang for helping me through this!

Going to make sure all the tests work in this branch now.

**Comment by adamwaite** [comment]
Hi @jedmund. Thanks for building this. Looks like you're doing a great job. If you manage to get all the tests back to green and give me the go ahead I'll create a dedicated Swift 3 branch before merging to master on the final release of Xcode 8.

Thanks!

**Comment by jedmund** [comment]
Hey @adamwaite, this should be done now as all the tests are working again. 

Let me know what you think!

**Comment by adamwaite** [comment]
Getting on this now, thanks @jedmund. Will stick a thanks bit in the README.

**Comment by adamwaite** [comment]
Great work @jedmund. I'll have a branch in the main repo soon. Just ironing a few little bits out with the latest Xcode beta.

**Comment by jedmund** [comment]
Thanks @adamwaite!

**Pull request merged**
