### PR TITLE
Add tvOS support

### PR DESCRIPTION
**Pull request by mihai8804858**
Thank you for this amazing framework. 👍 
A great feature will be ability to use it in tvOS apps.

### CODE REVIEW

**Comment by adamwaite** [comment]
Hey thanks for this. I'm heading away from my laptop for a week, but will take a look as soon as I'm back :)

**Comment by mihai8804858** [comment]
Sounds good. :)

**Comment by adamwaite** [comment]
Hey, looks good but I think this breaks the podfile? The sources have been moved into a new directory. If you could update the podfile I'm happy to merge.

**Comment by mihai8804858** [comment]
Hey @adamwaite, I have update `.podspec` file to reflect new paths. Also change tvOS deplayment target to 9.0 to reflect target from `.podspec` file.

**Comment by adamwaite** [comment]
Thanks man, good work.

**Pull request merged**
